Some error occurred!:
Left-hand-side of '42 => someOtherThing' is not a Boolean value.
However, using the try catch block we can still get here in spite of the error!

Something else happened:
[{"why use return, when we can throw things around"}, "??"]

Language error: 'om + om' is undefined.

Error in "throw("the end is near")":
Uncaught user exception: "the end is near"
